### ISSUE TITLE
Changing the default colors

### ISSUE THREAD

**Issue by kchr** [donnemartin/haxor-news#104]
Hi,

I am trying to configure the colors used by the haxor-news shell.

It looks like you are using prompt_toolkit and pygmentize, but the style name seems to be hardcoded with "vim" as value. What is the intended method of configuring this setting?

**Comment by donnemartin** [comment]
Hi @kchr, check out this section of the docs to change the theme: https://github.com/donnemartin/haxor-news#customizable-highlighting

**Comment by kchr** [comment]
@donnemartin  Thanks for the quick response and an awesome project!

**Comment by kchr** [comment]
@donnemartin It doesn't look like the prompt color can be changed. Is it using a specific terminal color for this, so I could change it in my terminal color scheme?
