### ISSUE TITLE
Tests seem to depend on network

### ISSUE THREAD

**Issue by matthiasbeyer** [donnemartin/haxor-news#129]
It seems that the tests depend on network access.

Because of this, we [disabled tests in nixpkgs](https://github.com/NixOS/nixpkgs/pull/35273/commits/70c031d300465f8ec7120cd18c3d21eaa799fa7f) for haxor-news.

Please either remove the tests which depend on network or provide a functionality to switch them off easily.

**Comment by donnemartin** [comment]
@matthiasbeyer thanks for reporting!

**Comment by donnemartin** [comment]
This should now be fixed with https://github.com/donnemartin/haxor-news/pull/177.
