### ISSUE TITLE
Command for exiting 'haxor' terminal

### ISSUE THREAD

**Issue by jashgala** [donnemartin/haxor-news#51]
Hi...

I think it would be a good thing to have a command that can help exit from the `haxor` command line.

Currently F10 is the key used for this purpose. However, in some terminals the key may be bound to some other function. Like in my case I am using the GNOME Terminal (3.6.2) that comes with Linux Mint. In this pressing F10 opens the file menu.

Ctrl+C, exit, halt, quit don't work for quiting the `haxor` command line to get to the original command line. It would be great if such a functionality could be added.

**Comment by donnemartin** [comment]
Hi, currently ctrl-c does a keyboard interrupt and ctrl-d exits the app, discussed in this issue:

https://github.com/awslabs/aws-shell/pull/50

>It seems to be the more standard behavior to use ctrl-c to keyboard interrupt and ctrl-d to exit the app. 

Perhaps this is not really 'standard' or 'discoverable' though and maybe an exit type of command would help.  Curious if that would also be discoverable.

I guess I'm wondering whether something in the README (or in the app itself) we should let users know how to quit.

**Comment by jashgala** [comment]
I didn't know about ctrl-d, though **I tried ctrl-c and it did not work on my system**. Also since it is more of a customized shell prompt than an interpreter, I  think having a command to exit may be a good idea. Will have to also see why ctrl-c isn't closing the haxor CLI.

**Comment by donnemartin** [comment]
>I tried ctrl-c and it did not work on my system. Will have to see why ctrl-c isn't closing the haxor CLI.

Sorry for the confusion, by keyboard interrupt I mean it will cancel the current command.

>Also since it is more of a customized shell prompt than an interpreter, I think having a command to exit may be a good idea.

I think that's a fair point, I'll check out the PR, thanks!

**Comment by donnemartin** [comment]
Merged with https://github.com/donnemartin/haxor-news/pull/52, thanks!
