### ISSUE TITLE
[feature request] Sharing posts, TTS

### ISSUE THREAD

**Issue by IOAyman** [donnemartin/haxor-news#58]
- It would be nice to be able to tweet one post (link and description) directly from the cli.
- Or, alternatively, be able to copy one post link (and the description, if wanted) to the clipboard directly from the cli as well.
- I think a text-to-speech integration would be great!

**Comment by donnemartin** [comment]
Thanks for the suggestion!  

This seems very similar to https://github.com/donnemartin/haxor-news/issues/43, I'll add your suggestions to that ticket.  

Let's use https://github.com/donnemartin/haxor-news/issues/43 going forward.
